### ISSUE TITLE
What probe do you use for this project (and RP2040 in general)?

### ISSUE THREAD

**Issue by mryndzionek** [kalkyl/st7735-embassy#4]
As in the title. I've tried STLink, but doesn't seem to recognize RP2040.

**Comment by kalkyl** [comment]
> As in the title. I've tried STLink, but doesn't seem to recognize RP2040.

You can use any DAP probe, i usually use an rp pico flashed with this image https://raw.githubusercontent.com/9names/binary-bits/main/rust-dap-pico-ramexec-setclock.uf2

Swclk = pin 2
Swdio = pin 3

**Comment by kalkyl** [comment]
(...however the examples in this project are written for nrf52)

**Comment by mryndzionek** [comment]
Oh yeah, sorry, I should have asked in https://github.com/kalkyl/ssd1306-async/blob/main/examples/.cargo/config.toml . Thanks for the info. I wasn't aware of https://github.com/9names/binary-bits .
